name: OpenWrt Builder - Z8103AX (Optimized)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

    - name: Cache build directories
      uses: actions/cache@v4
      with:
        path: |
          dl
          build_dir
          staging_dir
        key: ${{ runner.os }}-openwrt-${{ hashFiles('**/.config') }}

    - name: Download OpenWrt Source
      run: |
        git clone https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy Custom DTS
      run: |
        cp -f patches/dts/z8103ax.dts openwrt/target/linux/mediatek/dts/

    - name: Configure Target (Optimized)
      run: |
        cd openwrt
        rm -f .config
        # Target device
        echo "CONFIG_TARGET_mediatek_mt798x=y" >> .config
        echo "CONFIG_TARGET_mediatek_mt798x_DEVICE_z8103ax=y" >> .config
        
        # Minimal LuCI
        echo "CONFIG_PACKAGE_luci=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-opkg=y" >> .config
        echo "CONFIG_PACKAGE_luci-theme-bootstrap=y" >> .config

        # Disable heavy packages
        echo "# Disable Rust-related" >> .config
        echo "CONFIG_PACKAGE_rustc=n" >> .config
        echo "CONFIG_PACKAGE_cargo=n" >> .config
        echo "# Disable NodeJS" >> .config
        echo "CONFIG_PACKAGE_node=n" >> .config
        echo "CONFIG_PACKAGE_nodejs=n" >> .config
        echo "# Disable GoLang" >> .config
        echo "CONFIG_PACKAGE_golang=n" >> .config
        echo "# Disable Docker" >> .config
        echo "CONFIG_PACKAGE_docker=n" >> .config
        echo "CONFIG_PACKAGE_dockerd=n" >> .config
        echo "# Disable Samba4" >> .config
        echo "CONFIG_PACKAGE_samba4-server=n" >> .config
        echo "CONFIG_PACKAGE_samba4-libs=n" >> .config
        echo "# Disable PHP" >> .config
        echo "CONFIG_PACKAGE_php8=n" >> .config
        echo "CONFIG_PACKAGE_php8-cli=n" >> .config
        echo "# Disable Python big packages" >> .config
        echo "CONFIG_PACKAGE_python3=n" >> .config
        echo "CONFIG_PACKAGE_python3-pip=n" >> .config

        make defconfig

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) download
        make -j$(nproc) || make -j1 V=s

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-z8103ax-firmware
        path: openwrt/bin/targets/
